//
//  UIColorNameExtension.swift
//  Scrile
//
//  Created by Bram Seynhaeve on 04/07/2018.
//  Copyright © 2018 In The Pocket. All rights reserved.
//

import UIKit

extension UIColor {
    private static var names = [
        "Black": UIColor(hex: "000000"),
        "Navy Blue": UIColor(hex: "000080"),
        "Dark Blue": UIColor(hex: "0000C8"),
        "Blue": UIColor(hex: "0000FF"),
        "Stratos": UIColor(hex: "000741"),
        "Swamp": UIColor(hex: "001B1C"),
        "Resolution Blue": UIColor(hex: "002387"),
        "Deep Fir": UIColor(hex: "002900"),
        "Burnham": UIColor(hex: "002E20"),
        "International Klein Blue": UIColor(hex: "002FA7"),
        "Prussian Blue": UIColor(hex: "003153"),
        "Midnight Blue": UIColor(hex: "003366"),
        "Smalt": UIColor(hex: "003399"),
        "Deep Teal": UIColor(hex: "003532"),
        "Cyprus": UIColor(hex: "003E40"),
        "Kaitoke Green": UIColor(hex: "004620"),
        "Cobalt": UIColor(hex: "0047AB"),
        "Crusoe": UIColor(hex: "004816"),
        "Sherpa Blue": UIColor(hex: "004950"),
        "Endeavour": UIColor(hex: "0056A7"),
        "Camarone": UIColor(hex: "00581A"),
        "Science Blue": UIColor(hex: "0066CC"),
        "Blue Ribbon": UIColor(hex: "0066FF"),
        "Tropical Rain Forest": UIColor(hex: "00755E"),
        "Allports": UIColor(hex: "0076A3"),
        "Deep Cerulean": UIColor(hex: "007BA7"),
        "Lochmara": UIColor(hex: "007EC7"),
        "Azure Radiance": UIColor(hex: "007FFF"),
        "Teal": UIColor(hex: "008080"),
        "Bondi Blue": UIColor(hex: "0095B6"),
        "Pacific Blue": UIColor(hex: "009DC4"),
        "Persian Green": UIColor(hex: "00A693"),
        "Jade": UIColor(hex: "00A86B"),
        "Caribbean Green": UIColor(hex: "00CC99"),
        "Robin's Egg Blue": UIColor(hex: "00CCCC"),
        "Green": UIColor(hex: "00FF00"),
        "Spring Green": UIColor(hex: "00FF7F"),
        "Cyan / Aqua": UIColor(hex: "00FFFF"),
        "Blue Charcoal": UIColor(hex: "010D1A"),
        "Midnight": UIColor(hex: "011635"),
        "Holly": UIColor(hex: "011D13"),
        "Daintree": UIColor(hex: "012731"),
        "Cardin Green": UIColor(hex: "01361C"),
        "County Green": UIColor(hex: "01371A"),
        "Astronaut Blue": UIColor(hex: "013E62"),
        "Regal Blue": UIColor(hex: "013F6A"),
        "Aqua Deep": UIColor(hex: "014B43"),
        "Orient": UIColor(hex: "015E85"),
        "Blue Stone": UIColor(hex: "016162"),
        "Fun Green": UIColor(hex: "016D39"),
        "Pine Green": UIColor(hex: "01796F"),
        "Blue Lagoon": UIColor(hex: "017987"),
        "Deep Sea": UIColor(hex: "01826B"),
        "Green Haze": UIColor(hex: "01A368"),
        "English Holly": UIColor(hex: "022D15"),
        "Sherwood Green": UIColor(hex: "02402C"),
        "Congress Blue": UIColor(hex: "02478E"),
        "Evening Sea": UIColor(hex: "024E46"),
        "Bahama Blue": UIColor(hex: "026395"),
        "Observatory": UIColor(hex: "02866F"),
        "Cerulean": UIColor(hex: "02A4D3"),
        "Tangaroa": UIColor(hex: "03163C"),
        "Green Vogue": UIColor(hex: "032B52"),
        "Mosque": UIColor(hex: "036A6E"),
        "Midnight Moss": UIColor(hex: "041004"),
        "Black Pearl": UIColor(hex: "041322"),
        "Blue Whale": UIColor(hex: "042E4C"),
        "Zuccini": UIColor(hex: "044022"),
        "Teal Blue": UIColor(hex: "044259"),
        "Deep Cove": UIColor(hex: "051040"),
        "Gulf Blue": UIColor(hex: "051657"),
        "Venice Blue": UIColor(hex: "055989"),
        "Watercourse": UIColor(hex: "056F57"),
        "Catalina Blue": UIColor(hex: "062A78"),
        "Tiber": UIColor(hex: "063537"),
        "Gossamer": UIColor(hex: "069B81"),
        "Niagara": UIColor(hex: "06A189"),
        "Tarawera": UIColor(hex: "073A50"),
        "Jaguar": UIColor(hex: "080110"),
        "Black Bean": UIColor(hex: "081910"),
        "Deep Sapphire": UIColor(hex: "082567"),
        "Elf Green": UIColor(hex: "088370"),
        "Bright Turquoise": UIColor(hex: "08E8DE"),
        "Downriver": UIColor(hex: "092256"),
        "Palm Green": UIColor(hex: "09230F"),
        "Madison": UIColor(hex: "09255D"),
        "Bottle Green": UIColor(hex: "093624"),
        "Deep Sea Green": UIColor(hex: "095859"),
        "Salem": UIColor(hex: "097F4B"),
        "Black Russian": UIColor(hex: "0A001C"),
        "Dark Fern": UIColor(hex: "0A480D"),
        "Japanese Laurel": UIColor(hex: "0A6906"),
        "Atoll": UIColor(hex: "0A6F75"),
        "Cod Gray": UIColor(hex: "0B0B0B"),
        "Marshland": UIColor(hex: "0B0F08"),
        "Gordons Green": UIColor(hex: "0B1107"),
        "Black Forest": UIColor(hex: "0B1304"),
        "San Felix": UIColor(hex: "0B6207"),
        "Malachite": UIColor(hex: "0BDA51"),
        "Ebony": UIColor(hex: "0C0B1D"),
        "Woodsmoke": UIColor(hex: "0C0D0F"),
        "Racing Green": UIColor(hex: "0C1911"),
        "Surfie Green": UIColor(hex: "0C7A79"),
        "Blue Chill": UIColor(hex: "0C8990"),
        "Black Rock": UIColor(hex: "0D0332"),
        "Bunker": UIColor(hex: "0D1117"),
        "Aztec": UIColor(hex: "0D1C19"),
        "Bush": UIColor(hex: "0D2E1C"),
        "Cinder": UIColor(hex: "0E0E18"),
        "Firefly": UIColor(hex: "0E2A30"),
        "Torea Bay": UIColor(hex: "0F2D9E"),
        "Vulcan": UIColor(hex: "10121D"),
        "Green Waterloo": UIColor(hex: "101405"),
        "Eden": UIColor(hex: "105852"),
        "Arapawa": UIColor(hex: "110C6C"),
        "Ultramarine": UIColor(hex: "120A8F"),
        "Elephant": UIColor(hex: "123447"),
        "Jewel": UIColor(hex: "126B40"),
        "Diesel": UIColor(hex: "130000"),
        "Asphalt": UIColor(hex: "130A06"),
        "Blue Zodiac": UIColor(hex: "13264D"),
        "Parsley": UIColor(hex: "134F19"),
        "Nero": UIColor(hex: "140600"),
        "Tory Blue": UIColor(hex: "1450AA"),
        "Bunting": UIColor(hex: "151F4C"),
        "Denim": UIColor(hex: "1560BD"),
        "Genoa": UIColor(hex: "15736B"),
        "Mirage": UIColor(hex: "161928"),
        "Hunter Green": UIColor(hex: "161D10"),
        "Big Stone": UIColor(hex: "162A40"),
        "Celtic": UIColor(hex: "163222"),
        "Timber Green": UIColor(hex: "16322C"),
        "Gable Green": UIColor(hex: "163531"),
        "Pine Tree": UIColor(hex: "171F04"),
        "Chathams Blue": UIColor(hex: "175579"),
        "Deep Forest Green": UIColor(hex: "182D09"),
        "Blumine": UIColor(hex: "18587A"),
        "Palm Leaf": UIColor(hex: "19330E"),
        "Nile Blue": UIColor(hex: "193751"),
        "Fun Blue": UIColor(hex: "1959A8"),
        "Lucky Point": UIColor(hex: "1A1A68"),
        "Mountain Meadow": UIColor(hex: "1AB385"),
        "Tolopea": UIColor(hex: "1B0245"),
        "Haiti": UIColor(hex: "1B1035"),
        "Deep Koamaru": UIColor(hex: "1B127B"),
        "Acadia": UIColor(hex: "1B1404"),
        "Seaweed": UIColor(hex: "1B2F11"),
        "Biscay": UIColor(hex: "1B3162"),
        "Matisse": UIColor(hex: "1B659D"),
        "Crowshead": UIColor(hex: "1C1208"),
        "Rangoon Green": UIColor(hex: "1C1E13"),
        "Persian Blue": UIColor(hex: "1C39BB"),
        "Everglade": UIColor(hex: "1C402E"),
        "Elm": UIColor(hex: "1C7C7D"),
        "Green Pea": UIColor(hex: "1D6142"),
        "Creole": UIColor(hex: "1E0F04"),
        "Karaka": UIColor(hex: "1E1609"),
        "El Paso": UIColor(hex: "1E1708"),
        "Cello": UIColor(hex: "1E385B"),
        "Te Papa Green": UIColor(hex: "1E433C"),
        "Dodger Blue": UIColor(hex: "1E90FF"),
        "Eastern Blue": UIColor(hex: "1E9AB0"),
        "Night Rider": UIColor(hex: "1F120F"),
        "Java": UIColor(hex: "1FC2C2"),
        "Jacksons Purple": UIColor(hex: "20208D"),
        "Cloud Burst": UIColor(hex: "202E54"),
        "Blue Dianne": UIColor(hex: "204852"),
        "Eternity": UIColor(hex: "211A0E"),
        "Deep Blue": UIColor(hex: "220878"),
        "Forest Green": UIColor(hex: "228B22"),
        "Mallard": UIColor(hex: "233418"),
        "Violet": UIColor(hex: "240A40"),
        "Kilamanjaro": UIColor(hex: "240C02"),
        "Log Cabin": UIColor(hex: "242A1D"),
        "Black Olive": UIColor(hex: "242E16"),
        "Green House": UIColor(hex: "24500F"),
        "Graphite": UIColor(hex: "251607"),
        "Cannon Black": UIColor(hex: "251706"),
        "Port Gore": UIColor(hex: "251F4F"),
        "Shark": UIColor(hex: "25272C"),
        "Green Kelp": UIColor(hex: "25311C"),
        "Curious Blue": UIColor(hex: "2596D1"),
        "Paua": UIColor(hex: "260368"),
        "Paris M": UIColor(hex: "26056A"),
        "Wood Bark": UIColor(hex: "261105"),
        "Gondola": UIColor(hex: "261414"),
        "Steel Gray": UIColor(hex: "262335"),
        "Ebony Clay": UIColor(hex: "26283B"),
        "Bay of Many": UIColor(hex: "273A81"),
        "Plantation": UIColor(hex: "27504B"),
        "Eucalyptus": UIColor(hex: "278A5B"),
        "Oil": UIColor(hex: "281E15"),
        "Astronaut": UIColor(hex: "283A77"),
        "Mariner": UIColor(hex: "286ACD"),
        "Violent Violet": UIColor(hex: "290C5E"),
        "Bastille": UIColor(hex: "292130"),
        "Zeus": UIColor(hex: "292319"),
        "Charade": UIColor(hex: "292937"),
        "Jelly Bean": UIColor(hex: "297B9A"),
        "Jungle Green": UIColor(hex: "29AB87"),
        "Cherry Pie": UIColor(hex: "2A0359"),
        "Coffee Bean": UIColor(hex: "2A140E"),
        "Baltic Sea": UIColor(hex: "2A2630"),
        "Turtle Green": UIColor(hex: "2A380B"),
        "Cerulean Blue": UIColor(hex: "2A52BE"),
        "Sepia Black": UIColor(hex: "2B0202"),
        "Valhalla": UIColor(hex: "2B194F"),
        "Heavy Metal": UIColor(hex: "2B3228"),
        "Blue Gem": UIColor(hex: "2C0E8C"),
        "Revolver": UIColor(hex: "2C1632"),
        "Bleached Cedar": UIColor(hex: "2C2133"),
        "Lochinvar": UIColor(hex: "2C8C84"),
        "Mikado": UIColor(hex: "2D2510"),
        "Outer Space": UIColor(hex: "2D383A"),
        "St Tropaz": UIColor(hex: "2D569B"),
        "Jacaranda": UIColor(hex: "2E0329"),
        "Jacko Bean": UIColor(hex: "2E1905"),
        "Rangitoto": UIColor(hex: "2E3222"),
        "Rhino": UIColor(hex: "2E3F62"),
        "Sea Green": UIColor(hex: "2E8B57"),
        "Scooter": UIColor(hex: "2EBFD4"),
        "Onion": UIColor(hex: "2F270E"),
        "Governor Bay": UIColor(hex: "2F3CB3"),
        "Sapphire": UIColor(hex: "2F519E"),
        "Spectra": UIColor(hex: "2F5A57"),
        "Casal": UIColor(hex: "2F6168"),
        "Melanzane": UIColor(hex: "300529"),
        "Cocoa Brown": UIColor(hex: "301F1E"),
        "Woodrush": UIColor(hex: "302A0F"),
        "San Juan": UIColor(hex: "304B6A"),
        "Turquoise": UIColor(hex: "30D5C8"),
        "Eclipse": UIColor(hex: "311C17"),
        "Pickled Bluewood": UIColor(hex: "314459"),
        "Azure": UIColor(hex: "315BA1"),
        "Calypso": UIColor(hex: "31728D"),
        "Paradiso": UIColor(hex: "317D82"),
        "Persian Indigo": UIColor(hex: "32127A"),
        "Blackcurrant": UIColor(hex: "32293A"),
        "Mine Shaft": UIColor(hex: "323232"),
        "Stromboli": UIColor(hex: "325D52"),
        "Bilbao": UIColor(hex: "327C14"),
        "Astral": UIColor(hex: "327DA0"),
        "Christalle": UIColor(hex: "33036B"),
        "Thunder": UIColor(hex: "33292F"),
        "Shamrock": UIColor(hex: "33CC99"),
        "Tamarind": UIColor(hex: "341515"),
        "Mardi Gras": UIColor(hex: "350036"),
        "Valentino": UIColor(hex: "350E42"),
        "Jagger": UIColor(hex: "350E57"),
        "Tuna": UIColor(hex: "353542"),
        "Chambray": UIColor(hex: "354E8C"),
        "Martinique": UIColor(hex: "363050"),
        "Tuatara": UIColor(hex: "363534"),
        "Waiouru": UIColor(hex: "363C0D"),
        "Ming": UIColor(hex: "36747D"),
        "La Palma": UIColor(hex: "368716"),
        "Chocolate": UIColor(hex: "370202"),
        "Clinker": UIColor(hex: "371D09"),
        "Brown Tumbleweed": UIColor(hex: "37290E"),
        "Birch": UIColor(hex: "373021"),
        "Oracle": UIColor(hex: "377475"),
        "Blue Diamond": UIColor(hex: "380474"),
        "Grape": UIColor(hex: "381A51"),
        "Dune": UIColor(hex: "383533"),
        "Oxford Blue": UIColor(hex: "384555"),
        "Clover": UIColor(hex: "384910"),
        "Limed Spruce": UIColor(hex: "394851"),
        "Dell": UIColor(hex: "396413"),
        "Toledo": UIColor(hex: "3A0020"),
        "Sambuca": UIColor(hex: "3A2010"),
        "Jacarta": UIColor(hex: "3A2A6A"),
        "William": UIColor(hex: "3A686C"),
        "Killarney": UIColor(hex: "3A6A47"),
        "Keppel": UIColor(hex: "3AB09E"),
        "Temptress": UIColor(hex: "3B000B"),
        "Aubergine": UIColor(hex: "3B0910"),
        "Jon": UIColor(hex: "3B1F1F"),
        "Treehouse": UIColor(hex: "3B2820"),
        "Amazon": UIColor(hex: "3B7A57"),
        "Boston Blue": UIColor(hex: "3B91B4"),
        "Windsor": UIColor(hex: "3C0878"),
        "Rebel": UIColor(hex: "3C1206"),
        "Meteorite": UIColor(hex: "3C1F76"),
        "Dark Ebony": UIColor(hex: "3C2005"),
        "Camouflage": UIColor(hex: "3C3910"),
        "Bright Gray": UIColor(hex: "3C4151"),
        "Cape Cod": UIColor(hex: "3C4443"),
        "Lunar Green": UIColor(hex: "3C493A"),
        "Bean  ": UIColor(hex: "3D0C02"),
        "Bistre": UIColor(hex: "3D2B1F"),
        "Goblin": UIColor(hex: "3D7D52"),
        "Kingfisher Daisy": UIColor(hex: "3E0480"),
        "Cedar": UIColor(hex: "3E1C14"),
        "English Walnut": UIColor(hex: "3E2B23"),
        "Black Marlin": UIColor(hex: "3E2C1C"),
        "Ship Gray": UIColor(hex: "3E3A44"),
        "Pelorous": UIColor(hex: "3EABBF"),
        "Bronze": UIColor(hex: "3F2109"),
        "Cola": UIColor(hex: "3F2500"),
        "Madras": UIColor(hex: "3F3002"),
        "Minsk": UIColor(hex: "3F307F"),
        "Cabbage Pont": UIColor(hex: "3F4C3A"),
        "Tom Thumb": UIColor(hex: "3F583B"),
        "Mineral Green": UIColor(hex: "3F5D53"),
        "Puerto Rico": UIColor(hex: "3FC1AA"),
        "Harlequin": UIColor(hex: "3FFF00"),
        "Brown Pod": UIColor(hex: "401801"),
        "Cork": UIColor(hex: "40291D"),
        "Masala": UIColor(hex: "403B38"),
        "Thatch Green": UIColor(hex: "403D19"),
        "Fiord": UIColor(hex: "405169"),
        "Viridian": UIColor(hex: "40826D"),
        "Chateau Green": UIColor(hex: "40A860"),
        "Ripe Plum": UIColor(hex: "410056"),
        "Paco": UIColor(hex: "411F10"),
        "Deep Oak": UIColor(hex: "412010"),
        "Merlin": UIColor(hex: "413C37"),
        "Gun Powder": UIColor(hex: "414257"),
        "East Bay": UIColor(hex: "414C7D"),
        "Royal Blue": UIColor(hex: "4169E1"),
        "Ocean Green": UIColor(hex: "41AA78"),
        "Burnt Maroon": UIColor(hex: "420303"),
        "Lisbon Brown": UIColor(hex: "423921"),
        "Faded Jade": UIColor(hex: "427977"),
        "Scarlet Gum": UIColor(hex: "431560"),
        "Iroko": UIColor(hex: "433120"),
        "Armadillo": UIColor(hex: "433E37"),
        "River Bed": UIColor(hex: "434C59"),
        "Green Leaf": UIColor(hex: "436A0D"),
        "Barossa": UIColor(hex: "44012D"),
        "Morocco Brown": UIColor(hex: "441D00"),
        "Mako": UIColor(hex: "444954"),
        "Kelp": UIColor(hex: "454936"),
        "San Marino": UIColor(hex: "456CAC"),
        "Picton Blue": UIColor(hex: "45B1E8"),
        "Loulou": UIColor(hex: "460B41"),
        "Crater Brown": UIColor(hex: "462425"),
        "Gray Asparagus": UIColor(hex: "465945"),
        "Steel Blue": UIColor(hex: "4682B4"),
        "Rustic Red": UIColor(hex: "480404"),
        "Bulgarian Rose": UIColor(hex: "480607"),
        "Clairvoyant": UIColor(hex: "480656"),
        "Cocoa Bean": UIColor(hex: "481C1C"),
        "Woody Brown": UIColor(hex: "483131"),
        "Taupe": UIColor(hex: "483C32"),
        "Van Cleef": UIColor(hex: "49170C"),
        "Brown Derby": UIColor(hex: "492615"),
        "Metallic Bronze": UIColor(hex: "49371B"),
        "Verdun Green": UIColor(hex: "495400"),
        "Blue Bayoux": UIColor(hex: "496679"),
        "Bismark": UIColor(hex: "497183"),
        "Bracken": UIColor(hex: "4A2A04"),
        "Deep Bronze": UIColor(hex: "4A3004"),
        "Mondo": UIColor(hex: "4A3C30"),
        "Tundora": UIColor(hex: "4A4244"),
        "Gravel": UIColor(hex: "4A444B"),
        "Trout": UIColor(hex: "4A4E5A"),
        "Pigment Indigo": UIColor(hex: "4B0082"),
        "Nandor": UIColor(hex: "4B5D52"),
        "Saddle": UIColor(hex: "4C3024"),
        "Abbey": UIColor(hex: "4C4F56"),
        "Blackberry": UIColor(hex: "4D0135"),
        "Cab Sav": UIColor(hex: "4D0A18"),
        "Indian Tan": UIColor(hex: "4D1E01"),
        "Cowboy": UIColor(hex: "4D282D"),
        "Livid Brown": UIColor(hex: "4D282E"),
        "Rock": UIColor(hex: "4D3833"),
        "Punga": UIColor(hex: "4D3D14"),
        "Bronzetone": UIColor(hex: "4D400F"),
        "Woodland": UIColor(hex: "4D5328"),
        "Mahogany": UIColor(hex: "4E0606"),
        "Bossanova": UIColor(hex: "4E2A5A"),
        "Matterhorn": UIColor(hex: "4E3B41"),
        "Bronze Olive": UIColor(hex: "4E420C"),
        "Mulled Wine": UIColor(hex: "4E4562"),
        "Axolotl": UIColor(hex: "4E6649"),
        "Wedgewood": UIColor(hex: "4E7F9E"),
        "Shakespeare": UIColor(hex: "4EABD1"),
        "Honey Flower": UIColor(hex: "4F1C70"),
        "Daisy Bush": UIColor(hex: "4F2398"),
        "Indigo": UIColor(hex: "4F69C6"),
        "Fern Green": UIColor(hex: "4F7942"),
        "Fruit Salad": UIColor(hex: "4F9D5D"),
        "Apple": UIColor(hex: "4FA83D"),
        "Mortar": UIColor(hex: "504351"),
        "Kashmir Blue": UIColor(hex: "507096"),
        "Cutty Sark": UIColor(hex: "507672"),
        "Emerald": UIColor(hex: "50C878"),
        "Emperor": UIColor(hex: "514649"),
        "Chalet Green": UIColor(hex: "516E3D"),
        "Como": UIColor(hex: "517C66"),
        "Smalt Blue": UIColor(hex: "51808F"),
        "Castro": UIColor(hex: "52001F"),
        "Maroon Oak": UIColor(hex: "520C17"),
        "Gigas": UIColor(hex: "523C94"),
        "Voodoo": UIColor(hex: "533455"),
        "Victoria": UIColor(hex: "534491"),
        "Hippie Green": UIColor(hex: "53824B"),
        "Heath": UIColor(hex: "541012"),
        "Judge Gray": UIColor(hex: "544333"),
        "Fuscous Gray": UIColor(hex: "54534D"),
        "Vida Loca": UIColor(hex: "549019"),
        "Cioccolato": UIColor(hex: "55280C"),
        "Saratoga": UIColor(hex: "555B10"),
        "Finlandia": UIColor(hex: "556D56"),
        "Havelock Blue": UIColor(hex: "5590D9"),
        "Fountain Blue": UIColor(hex: "56B4BE"),
        "Spring Leaves": UIColor(hex: "578363"),
        "Saddle Brown": UIColor(hex: "583401"),
        "Scarpa Flow": UIColor(hex: "585562"),
        "Cactus": UIColor(hex: "587156"),
        "Hippie Blue": UIColor(hex: "589AAF"),
        "Wine Berry": UIColor(hex: "591D35"),
        "Brown Bramble": UIColor(hex: "592804"),
        "Congo Brown": UIColor(hex: "593737"),
        "Millbrook": UIColor(hex: "594433"),
        "Waikawa Gray": UIColor(hex: "5A6E9C"),
        "Horizon": UIColor(hex: "5A87A0"),
        "Jambalaya": UIColor(hex: "5B3013"),
        "Bordeaux": UIColor(hex: "5C0120"),
        "Mulberry Wood": UIColor(hex: "5C0536"),
        "Carnaby Tan": UIColor(hex: "5C2E01"),
        "Comet": UIColor(hex: "5C5D75"),
        "Redwood": UIColor(hex: "5D1E0F"),
        "Don Juan": UIColor(hex: "5D4C51"),
        "Chicago": UIColor(hex: "5D5C58"),
        "Verdigris": UIColor(hex: "5D5E37"),
        "Dingley": UIColor(hex: "5D7747"),
        "Breaker Bay": UIColor(hex: "5DA19F"),
        "Kabul": UIColor(hex: "5E483E"),
        "Hemlock": UIColor(hex: "5E5D3B"),
        "Irish Coffee": UIColor(hex: "5F3D26"),
        "Mid Gray": UIColor(hex: "5F5F6E"),
        "Shuttle Gray": UIColor(hex: "5F6672"),
        "Aqua Forest": UIColor(hex: "5FA777"),
        "Tradewind": UIColor(hex: "5FB3AC"),
        "Horses Neck": UIColor(hex: "604913"),
        "Smoky": UIColor(hex: "605B73"),
        "Corduroy": UIColor(hex: "606E68"),
        "Danube": UIColor(hex: "6093D1"),
        "Espresso": UIColor(hex: "612718"),
        "Eggplant": UIColor(hex: "614051"),
        "Costa Del Sol": UIColor(hex: "615D30"),
        "Glade Green": UIColor(hex: "61845F"),
        "Buccaneer": UIColor(hex: "622F30"),
        "Quincy": UIColor(hex: "623F2D"),
        "Butterfly Bush": UIColor(hex: "624E9A"),
        "West Coast": UIColor(hex: "625119"),
        "Finch": UIColor(hex: "626649"),
        "Patina": UIColor(hex: "639A8F"),
        "Fern": UIColor(hex: "63B76C"),
        "Blue Violet": UIColor(hex: "6456B7"),
        "Dolphin": UIColor(hex: "646077"),
        "Storm Dust": UIColor(hex: "646463"),
        "Siam": UIColor(hex: "646A54"),
        "Nevada": UIColor(hex: "646E75"),
        "Cornflower Blue": UIColor(hex: "6495ED"),
        "Viking": UIColor(hex: "64CCDB"),
        "Rosewood": UIColor(hex: "65000B"),
        "Cherrywood": UIColor(hex: "651A14"),
        "Purple Heart": UIColor(hex: "652DC1"),
        "Fern Frond": UIColor(hex: "657220"),
        "Willow Grove": UIColor(hex: "65745D"),
        "Hoki": UIColor(hex: "65869F"),
        "Pompadour": UIColor(hex: "660045"),
        "Purple": UIColor(hex: "660099"),
        "Tyrian Purple": UIColor(hex: "66023C"),
        "Dark Tan": UIColor(hex: "661010"),
        "Silver Tree": UIColor(hex: "66B58F"),
        "Bright Green": UIColor(hex: "66FF00"),
        "Screamin' Green": UIColor(hex: "66FF66"),
        "Black Rose": UIColor(hex: "67032D"),
        "Scampi": UIColor(hex: "675FA6"),
        "Ironside Gray": UIColor(hex: "676662"),
        "Viridian Green": UIColor(hex: "678975"),
        "Christi": UIColor(hex: "67A712"),
        "Nutmeg Wood Finish": UIColor(hex: "683600"),
        "Zambezi": UIColor(hex: "685558"),
        "Salt Box": UIColor(hex: "685E6E"),
        "Tawny Port": UIColor(hex: "692545"),
        "Finn": UIColor(hex: "692D54"),
        "Scorpion": UIColor(hex: "695F62"),
        "Lynch": UIColor(hex: "697E9A"),
        "Spice": UIColor(hex: "6A442E"),
        "Himalaya": UIColor(hex: "6A5D1B"),
        "Soya Bean": UIColor(hex: "6A6051"),
        "Hairy Heath": UIColor(hex: "6B2A14"),
        "Royal Purple": UIColor(hex: "6B3FA0"),
        "Shingle Fawn": UIColor(hex: "6B4E31"),
        "Dorado": UIColor(hex: "6B5755"),
        "Bermuda Gray": UIColor(hex: "6B8BA2"),
        "Olive Drab": UIColor(hex: "6B8E23"),
        "Eminence": UIColor(hex: "6C3082"),
        "Turquoise Blue": UIColor(hex: "6CDAE7"),
        "Lonestar": UIColor(hex: "6D0101"),
        "Pine Cone": UIColor(hex: "6D5E54"),
        "Dove Gray": UIColor(hex: "6D6C6C"),
        "Juniper": UIColor(hex: "6D9292"),
        "Gothic": UIColor(hex: "6D92A1"),
        "Red Oxide": UIColor(hex: "6E0902"),
        "Moccaccino": UIColor(hex: "6E1D14"),
        "Pickled Bean": UIColor(hex: "6E4826"),
        "Dallas": UIColor(hex: "6E4B26"),
        "Kokoda": UIColor(hex: "6E6D57"),
        "Pale Sky": UIColor(hex: "6E7783"),
        "Cafe Royale": UIColor(hex: "6F440C"),
        "Flint": UIColor(hex: "6F6A61"),
        "Highland": UIColor(hex: "6F8E63"),
        "Limeade": UIColor(hex: "6F9D02"),
        "Downy": UIColor(hex: "6FD0C5"),
        "Persian Plum": UIColor(hex: "701C1C"),
        "Sepia": UIColor(hex: "704214"),
        "Antique Bronze": UIColor(hex: "704A07"),
        "Ferra": UIColor(hex: "704F50"),
        "Coffee": UIColor(hex: "706555"),
        "Slate Gray": UIColor(hex: "708090"),
        "Cedar Wood Finish": UIColor(hex: "711A00"),
        "Metallic Copper": UIColor(hex: "71291D"),
        "Affair": UIColor(hex: "714693"),
        "Studio": UIColor(hex: "714AB2"),
        "Tobacco Brown": UIColor(hex: "715D47"),
        "Yellow Metal": UIColor(hex: "716338"),
        "Peat": UIColor(hex: "716B56"),
        "Olivetone": UIColor(hex: "716E10"),
        "Storm Gray": UIColor(hex: "717486"),
        "Sirocco": UIColor(hex: "718080"),
        "Aquamarine Blue": UIColor(hex: "71D9E2"),
        "Venetian Red": UIColor(hex: "72010F"),
        "Old Copper": UIColor(hex: "724A2F"),
        "Go Ben": UIColor(hex: "726D4E"),
        "Raven": UIColor(hex: "727B89"),
        "Seance": UIColor(hex: "731E8F"),
        "Raw Umber": UIColor(hex: "734A12"),
        "Kimberly": UIColor(hex: "736C9F"),
        "Crocodile": UIColor(hex: "736D58"),
        "Crete": UIColor(hex: "737829"),
        "Xanadu": UIColor(hex: "738678"),
        "Spicy Mustard": UIColor(hex: "74640D"),
        "Limed Ash": UIColor(hex: "747D63"),
        "Rolling Stone": UIColor(hex: "747D83"),
        "Blue Smoke": UIColor(hex: "748881"),
        "Laurel": UIColor(hex: "749378"),
        "Mantis": UIColor(hex: "74C365"),
        "Russett": UIColor(hex: "755A57"),
        "Deluge": UIColor(hex: "7563A8"),
        "Cosmic": UIColor(hex: "76395D"),
        "Blue Marguerite": UIColor(hex: "7666C6"),
        "Lima": UIColor(hex: "76BD17"),
        "Sky Blue": UIColor(hex: "76D7EA"),
        "Dark Burgundy": UIColor(hex: "770F05"),
        "Crown of Thorns": UIColor(hex: "771F1F"),
        "Walnut": UIColor(hex: "773F1A"),
        "Pablo": UIColor(hex: "776F61"),
        "Pacifika": UIColor(hex: "778120"),
        "Oxley": UIColor(hex: "779E86"),
        "Pastel Green": UIColor(hex: "77DD77"),
        "Japanese Maple": UIColor(hex: "780109"),
        "Mocha": UIColor(hex: "782D19"),
        "Peanut": UIColor(hex: "782F16"),
        "Camouflage Green": UIColor(hex: "78866B"),
        "Wasabi": UIColor(hex: "788A25"),
        "Ship Cove": UIColor(hex: "788BBA"),
        "Sea Nymph": UIColor(hex: "78A39C"),
        "Roman Coffee": UIColor(hex: "795D4C"),
        "Old Lavender": UIColor(hex: "796878"),
        "Rum": UIColor(hex: "796989"),
        "Fedora": UIColor(hex: "796A78"),
        "Sandstone": UIColor(hex: "796D62"),
        "Spray": UIColor(hex: "79DEEC"),
        "Siren": UIColor(hex: "7A013A"),
        "Fuchsia Blue": UIColor(hex: "7A58C1"),
        "Boulder": UIColor(hex: "7A7A7A"),
        "Wild Blue Yonder": UIColor(hex: "7A89B8"),
        "De York": UIColor(hex: "7AC488"),
        "Red Beech": UIColor(hex: "7B3801"),
        "Cinnamon": UIColor(hex: "7B3F00"),
        "Yukon Gold": UIColor(hex: "7B6608"),
        "Tapa": UIColor(hex: "7B7874"),
        "Waterloo ": UIColor(hex: "7B7C94"),
        "Flax Smoke": UIColor(hex: "7B8265"),
        "Amulet": UIColor(hex: "7B9F80"),
        "Asparagus": UIColor(hex: "7BA05B"),
        "Kenyan Copper": UIColor(hex: "7C1C05"),
        "Pesto": UIColor(hex: "7C7631"),
        "Topaz": UIColor(hex: "7C778A"),
        "Concord": UIColor(hex: "7C7B7A"),
        "Jumbo": UIColor(hex: "7C7B82"),
        "Trendy Green": UIColor(hex: "7C881A"),
        "Gumbo": UIColor(hex: "7CA1A6"),
        "Acapulco": UIColor(hex: "7CB0A1"),
        "Neptune": UIColor(hex: "7CB7BB"),
        "Pueblo": UIColor(hex: "7D2C14"),
        "Bay Leaf": UIColor(hex: "7DA98D"),
        "Malibu": UIColor(hex: "7DC8F7"),
        "Bermuda": UIColor(hex: "7DD8C6"),
        "Copper Canyon": UIColor(hex: "7E3A15"),
        "Claret": UIColor(hex: "7F1734"),
        "Peru Tan": UIColor(hex: "7F3A02"),
        "Falcon": UIColor(hex: "7F626D"),
        "Mobster": UIColor(hex: "7F7589"),
        "Moody Blue": UIColor(hex: "7F76D3"),
        "Chartreuse": UIColor(hex: "7FFF00"),
        "Aquamarine": UIColor(hex: "7FFFD4"),
        "Maroon": UIColor(hex: "800000"),
        "Rose Bud Cherry": UIColor(hex: "800B47"),
        "Falu Red": UIColor(hex: "801818"),
        "Red Robin": UIColor(hex: "80341F"),
        "Vivid Violet": UIColor(hex: "803790"),
        "Russet": UIColor(hex: "80461B"),
        "Friar Gray": UIColor(hex: "807E79"),
        "Olive": UIColor(hex: "808000"),
        "Gray": UIColor(hex: "808080"),
        "Gulf Stream": UIColor(hex: "80B3AE"),
        "Glacier": UIColor(hex: "80B3C4"),
        "Seagull": UIColor(hex: "80CCEA"),
        "Nutmeg": UIColor(hex: "81422C"),
        "Spicy Pink": UIColor(hex: "816E71"),
        "Empress": UIColor(hex: "817377"),
        "Spanish Green": UIColor(hex: "819885"),
        "Sand Dune": UIColor(hex: "826F65"),
        "Gunsmoke": UIColor(hex: "828685"),
        "Battleship Gray": UIColor(hex: "828F72"),
        "Merlot": UIColor(hex: "831923"),
        "Shadow": UIColor(hex: "837050"),
        "Chelsea Cucumber": UIColor(hex: "83AA5D"),
        "Monte Carlo": UIColor(hex: "83D0C6"),
        "Plum": UIColor(hex: "843179"),
        "Granny Smith": UIColor(hex: "84A0A0"),
        "Chetwode Blue": UIColor(hex: "8581D9"),
        "Bandicoot": UIColor(hex: "858470"),
        "Bali Hai": UIColor(hex: "859FAF"),
        "Half Baked": UIColor(hex: "85C4CC"),
        "Red Devil": UIColor(hex: "860111"),
        "Lotus": UIColor(hex: "863C3C"),
        "Ironstone": UIColor(hex: "86483C"),
        "Bull Shot": UIColor(hex: "864D1E"),
        "Rusty Nail": UIColor(hex: "86560A"),
        "Bitter": UIColor(hex: "868974"),
        "Regent Gray": UIColor(hex: "86949F"),
        "Disco": UIColor(hex: "871550"),
        "Americano": UIColor(hex: "87756E"),
        "Hurricane": UIColor(hex: "877C7B"),
        "Oslo Gray": UIColor(hex: "878D91"),
        "Sushi": UIColor(hex: "87AB39"),
        "Spicy Mix": UIColor(hex: "885342"),
        "Kumera": UIColor(hex: "886221"),
        "Suva Gray": UIColor(hex: "888387"),
        "Avocado": UIColor(hex: "888D65"),
        "Camelot": UIColor(hex: "893456"),
        "Solid Pink": UIColor(hex: "893843"),
        "Cannon Pink": UIColor(hex: "894367"),
        "Makara": UIColor(hex: "897D6D"),
        "Burnt Umber": UIColor(hex: "8A3324"),
        "True V": UIColor(hex: "8A73D6"),
        "Clay Creek": UIColor(hex: "8A8360"),
        "Monsoon": UIColor(hex: "8A8389"),
        "Stack": UIColor(hex: "8A8F8A"),
        "Jordy Blue": UIColor(hex: "8AB9F1"),
        "Electric Violet": UIColor(hex: "8B00FF"),
        "Monarch": UIColor(hex: "8B0723"),
        "Corn Harvest": UIColor(hex: "8B6B0B"),
        "Olive Haze": UIColor(hex: "8B8470"),
        "Schooner": UIColor(hex: "8B847E"),
        "Natural Gray": UIColor(hex: "8B8680"),
        "Mantle": UIColor(hex: "8B9C90"),
        "Portage": UIColor(hex: "8B9FEE"),
        "Envy": UIColor(hex: "8BA690"),
        "Cascade": UIColor(hex: "8BA9A5"),
        "Riptide": UIColor(hex: "8BE6D8"),
        "Cardinal Pink": UIColor(hex: "8C055E"),
        "Mule Fawn": UIColor(hex: "8C472F"),
        "Potters Clay": UIColor(hex: "8C5738"),
        "Trendy Pink": UIColor(hex: "8C6495"),
        "Paprika": UIColor(hex: "8D0226"),
        "Sanguine Brown": UIColor(hex: "8D3D38"),
        "Tosca": UIColor(hex: "8D3F3F"),
        "Cement": UIColor(hex: "8D7662"),
        "Granite Green": UIColor(hex: "8D8974"),
        "Manatee": UIColor(hex: "8D90A1"),
        "Polo Blue": UIColor(hex: "8DA8CC"),
        "Red Berry": UIColor(hex: "8E0000"),
        "Rope": UIColor(hex: "8E4D1E"),
        "Opium": UIColor(hex: "8E6F70"),
        "Domino": UIColor(hex: "8E775E"),
        "Mamba": UIColor(hex: "8E8190"),
        "Nepal": UIColor(hex: "8EABC1"),
        "Pohutukawa": UIColor(hex: "8F021C"),
        "El Salva": UIColor(hex: "8F3E33"),
        "Korma": UIColor(hex: "8F4B0E"),
        "Squirrel": UIColor(hex: "8F8176"),
        "Vista Blue": UIColor(hex: "8FD6B4"),
        "Burgundy": UIColor(hex: "900020"),
        "Old Brick": UIColor(hex: "901E1E"),
        "Hemp": UIColor(hex: "907874"),
        "Almond Frost": UIColor(hex: "907B71"),
        "Sycamore": UIColor(hex: "908D39"),
        "Sangria": UIColor(hex: "92000A"),
        "Cumin": UIColor(hex: "924321"),
        "Beaver": UIColor(hex: "926F5B"),
        "Stonewall": UIColor(hex: "928573"),
        "Venus": UIColor(hex: "928590"),
        "Medium Purple": UIColor(hex: "9370DB"),
        "Cornflower": UIColor(hex: "93CCEA"),
        "Algae Green": UIColor(hex: "93DFB8"),
        "Copper Rust": UIColor(hex: "944747"),
        "Arrowtown": UIColor(hex: "948771"),
        "Scarlett": UIColor(hex: "950015"),
        "Strikemaster": UIColor(hex: "956387"),
        "Mountain Mist": UIColor(hex: "959396"),
        "Carmine": UIColor(hex: "960018"),
        "Brown": UIColor(hex: "964B00"),
        "Leather": UIColor(hex: "967059"),
        "Purple Mountain's Majesty": UIColor(hex: "9678B6"),
        "Lavender Purple": UIColor(hex: "967BB6"),
        "Pewter": UIColor(hex: "96A8A1"),
        "Summer Green": UIColor(hex: "96BBAB"),
        "Au Chico": UIColor(hex: "97605D"),
        "Wisteria": UIColor(hex: "9771B5"),
        "Atlantis": UIColor(hex: "97CD2D"),
        "Vin Rouge": UIColor(hex: "983D61"),
        "Lilac Bush": UIColor(hex: "9874D3"),
        "Bazaar": UIColor(hex: "98777B"),
        "Hacienda": UIColor(hex: "98811B"),
        "Pale Oyster": UIColor(hex: "988D77"),
        "Mint Green": UIColor(hex: "98FF98"),
        "Fresh Eggplant": UIColor(hex: "990066"),
        "Violet Eggplant": UIColor(hex: "991199"),
        "Tamarillo": UIColor(hex: "991613"),
        "Totem Pole": UIColor(hex: "991B07"),
        "Copper Rose": UIColor(hex: "996666"),
        "Amethyst": UIColor(hex: "9966CC"),
        "Mountbatten Pink": UIColor(hex: "997A8D"),
        "Blue Bell": UIColor(hex: "9999CC"),
        "Prairie Sand": UIColor(hex: "9A3820"),
        "Toast": UIColor(hex: "9A6E61"),
        "Gurkha": UIColor(hex: "9A9577"),
        "Olivine": UIColor(hex: "9AB973"),
        "Shadow Green": UIColor(hex: "9AC2B8"),
        "Oregon": UIColor(hex: "9B4703"),
        "Lemon Grass": UIColor(hex: "9B9E8F"),
        "Stiletto": UIColor(hex: "9C3336"),
        "Hawaiian Tan": UIColor(hex: "9D5616"),
        "Gull Gray": UIColor(hex: "9DACB7"),
        "Pistachio": UIColor(hex: "9DC209"),
        "Granny Smith Apple": UIColor(hex: "9DE093"),
        "Anakiwa": UIColor(hex: "9DE5FF"),
        "Chelsea Gem": UIColor(hex: "9E5302"),
        "Sepia Skin": UIColor(hex: "9E5B40"),
        "Sage": UIColor(hex: "9EA587"),
        "Citron": UIColor(hex: "9EA91F"),
        "Rock Blue": UIColor(hex: "9EB1CD"),
        "Morning Glory": UIColor(hex: "9EDEE0"),
        "Cognac": UIColor(hex: "9F381D"),
        "Reef Gold": UIColor(hex: "9F821C"),
        "Star Dust": UIColor(hex: "9F9F9C"),
        "Santas Gray": UIColor(hex: "9FA0B1"),
        "Sinbad": UIColor(hex: "9FD7D3"),
        "Feijoa": UIColor(hex: "9FDD8C"),
        "Tabasco": UIColor(hex: "A02712"),
        "Buttered Rum": UIColor(hex: "A1750D"),
        "Hit Gray": UIColor(hex: "A1ADB5"),
        "Citrus": UIColor(hex: "A1C50A"),
        "Aqua Island": UIColor(hex: "A1DAD7"),
        "Water Leaf": UIColor(hex: "A1E9DE"),
        "Flirt": UIColor(hex: "A2006D"),
        "Rouge": UIColor(hex: "A23B6C"),
        "Cape Palliser": UIColor(hex: "A26645"),
        "Gray Chateau": UIColor(hex: "A2AAB3"),
        "Edward": UIColor(hex: "A2AEAB"),
        "Pharlap": UIColor(hex: "A3807B"),
        "Amethyst Smoke": UIColor(hex: "A397B4"),
        "Blizzard Blue": UIColor(hex: "A3E3ED"),
        "Delta": UIColor(hex: "A4A49D"),
        "Wistful": UIColor(hex: "A4A6D3"),
        "Green Smoke": UIColor(hex: "A4AF6E"),
        "Jazzberry Jam": UIColor(hex: "A50B5E"),
        "Zorba": UIColor(hex: "A59B91"),
        "Bahia": UIColor(hex: "A5CB0C"),
        "Roof Terracotta": UIColor(hex: "A62F20"),
        "Paarl": UIColor(hex: "A65529"),
        "Barley Corn": UIColor(hex: "A68B5B"),
        "Donkey Brown": UIColor(hex: "A69279"),
        "Dawn": UIColor(hex: "A6A29A"),
        "Mexican Red": UIColor(hex: "A72525"),
        "Luxor Gold": UIColor(hex: "A7882C"),
        "Rich Gold": UIColor(hex: "A85307"),
        "Reno Sand": UIColor(hex: "A86515"),
        "Coral Tree": UIColor(hex: "A86B6B"),
        "Dusty Gray": UIColor(hex: "A8989B"),
        "Dull Lavender": UIColor(hex: "A899E6"),
        "Tallow": UIColor(hex: "A8A589"),
        "Bud": UIColor(hex: "A8AE9C"),
        "Locust": UIColor(hex: "A8AF8E"),
        "Norway": UIColor(hex: "A8BD9F"),
        "Chinook": UIColor(hex: "A8E3BD"),
        "Gray Olive": UIColor(hex: "A9A491"),
        "Aluminium": UIColor(hex: "A9ACB6"),
        "Cadet Blue": UIColor(hex: "A9B2C3"),
        "Schist": UIColor(hex: "A9B497"),
        "Tower Gray": UIColor(hex: "A9BDBF"),
        "Perano": UIColor(hex: "A9BEF2"),
        "Opal": UIColor(hex: "A9C6C2"),
        "Night Shadz": UIColor(hex: "AA375A"),
        "Fire": UIColor(hex: "AA4203"),
        "Muesli": UIColor(hex: "AA8B5B"),
        "Sandal": UIColor(hex: "AA8D6F"),
        "Shady Lady": UIColor(hex: "AAA5A9"),
        "Logan": UIColor(hex: "AAA9CD"),
        "Spun Pearl": UIColor(hex: "AAABB7"),
        "Regent St Blue": UIColor(hex: "AAD6E6"),
        "Magic Mint": UIColor(hex: "AAF0D1"),
        "Lipstick": UIColor(hex: "AB0563"),
        "Royal Heath": UIColor(hex: "AB3472"),
        "Sandrift": UIColor(hex: "AB917A"),
        "Cold Purple": UIColor(hex: "ABA0D9"),
        "Bronco": UIColor(hex: "ABA196"),
        "Limed Oak": UIColor(hex: "AC8A56"),
        "East Side": UIColor(hex: "AC91CE"),
        "Lemon Ginger": UIColor(hex: "AC9E22"),
        "Napa": UIColor(hex: "ACA494"),
        "Hillary": UIColor(hex: "ACA586"),
        "Cloudy": UIColor(hex: "ACA59F"),
        "Silver Chalice": UIColor(hex: "ACACAC"),
        "Swamp Green": UIColor(hex: "ACB78E"),
        "Spring Rain": UIColor(hex: "ACCBB1"),
        "Conifer": UIColor(hex: "ACDD4D"),
        "Celadon": UIColor(hex: "ACE1AF"),
        "Mandalay": UIColor(hex: "AD781B"),
        "Casper": UIColor(hex: "ADBED1"),
        "Moss Green": UIColor(hex: "ADDFAD"),
        "Padua": UIColor(hex: "ADE6C4"),
        "Green Yellow": UIColor(hex: "ADFF2F"),
        "Hippie Pink": UIColor(hex: "AE4560"),
        "Desert": UIColor(hex: "AE6020"),
        "Bouquet": UIColor(hex: "AE809E"),
        "Medium Carmine": UIColor(hex: "AF4035"),
        "Apple Blossom": UIColor(hex: "AF4D43"),
        "Brown Rust": UIColor(hex: "AF593E"),
        "Driftwood": UIColor(hex: "AF8751"),
        "Alpine": UIColor(hex: "AF8F2C"),
        "Lucky": UIColor(hex: "AF9F1C"),
        "Martini": UIColor(hex: "AFA09E"),
        "Bombay": UIColor(hex: "AFB1B8"),
        "Pigeon Post": UIColor(hex: "AFBDD9"),
        "Cadillac": UIColor(hex: "B04C6A"),
        "Matrix": UIColor(hex: "B05D54"),
        "Tapestry": UIColor(hex: "B05E81"),
        "Mai Tai": UIColor(hex: "B06608"),
        "Del Rio": UIColor(hex: "B09A95"),
        "Powder Blue": UIColor(hex: "B0E0E6"),
        "Inch Worm": UIColor(hex: "B0E313"),
        "Bright Red": UIColor(hex: "B10000"),
        "Vesuvius": UIColor(hex: "B14A0B"),
        "Pumpkin Skin": UIColor(hex: "B1610B"),
        "Santa Fe": UIColor(hex: "B16D52"),
        "Teak": UIColor(hex: "B19461"),
        "Fringy Flower": UIColor(hex: "B1E2C1"),
        "Ice Cold": UIColor(hex: "B1F4E7"),
        "Shiraz": UIColor(hex: "B20931"),
        "Biloba Flower": UIColor(hex: "B2A1EA"),
        "Tall Poppy": UIColor(hex: "B32D29"),
        "Fiery Orange": UIColor(hex: "B35213"),
        "Hot Toddy": UIColor(hex: "B38007"),
        "Taupe Gray": UIColor(hex: "B3AF95"),
        "La Rioja": UIColor(hex: "B3C110"),
        "Well Read": UIColor(hex: "B43332"),
        "Blush": UIColor(hex: "B44668"),
        "Jungle Mist": UIColor(hex: "B4CFD3"),
        "Turkish Rose": UIColor(hex: "B57281"),
        "Lavender": UIColor(hex: "B57EDC"),
        "Mongoose": UIColor(hex: "B5A27F"),
        "Olive Green": UIColor(hex: "B5B35C"),
        "Jet Stream": UIColor(hex: "B5D2CE"),
        "Cruise": UIColor(hex: "B5ECDF"),
        "Hibiscus": UIColor(hex: "B6316C"),
        "Thatch": UIColor(hex: "B69D98"),
        "Heathered Gray": UIColor(hex: "B6B095"),
        "Eagle": UIColor(hex: "B6BAA4"),
        "Spindle": UIColor(hex: "B6D1EA"),
        "Gum Leaf": UIColor(hex: "B6D3BF"),
        "Rust": UIColor(hex: "B7410E"),
        "Muddy Waters": UIColor(hex: "B78E5C"),
        "Sahara": UIColor(hex: "B7A214"),
        "Husk": UIColor(hex: "B7A458"),
        "Nobel": UIColor(hex: "B7B1B1"),
        "Heather": UIColor(hex: "B7C3D0"),
        "Madang": UIColor(hex: "B7F0BE"),
        "Milano Red": UIColor(hex: "B81104"),
        "Copper": UIColor(hex: "B87333"),
        "Gimblet": UIColor(hex: "B8B56A"),
        "Green Spring": UIColor(hex: "B8C1B1"),
        "Celery": UIColor(hex: "B8C25D"),
        "Sail": UIColor(hex: "B8E0F9"),
        "Chestnut": UIColor(hex: "B94E48"),
        "Crail": UIColor(hex: "B95140"),
        "Marigold": UIColor(hex: "B98D28"),
        "Wild Willow": UIColor(hex: "B9C46A"),
        "Rainee": UIColor(hex: "B9C8AC"),
        "Guardsman Red": UIColor(hex: "BA0101"),
        "Rock Spray": UIColor(hex: "BA450C"),
        "Bourbon": UIColor(hex: "BA6F1E"),
        "Pirate Gold": UIColor(hex: "BA7F03"),
        "Nomad": UIColor(hex: "BAB1A2"),
        "Submarine": UIColor(hex: "BAC7C9"),
        "Charlotte": UIColor(hex: "BAEEF9"),
        "Medium Red Violet": UIColor(hex: "BB3385"),
        "Brandy Rose": UIColor(hex: "BB8983"),
        "Rio Grande": UIColor(hex: "BBD009"),
        "Surf": UIColor(hex: "BBD7C1"),
        "Powder Ash": UIColor(hex: "BCC9C2"),
        "Tuscany": UIColor(hex: "BD5E2E"),
        "Quicksand": UIColor(hex: "BD978E"),
        "Silk": UIColor(hex: "BDB1A8"),
        "Malta": UIColor(hex: "BDB2A1"),
        "Chatelle": UIColor(hex: "BDB3C7"),
        "Lavender Gray": UIColor(hex: "BDBBD7"),
        "French Gray": UIColor(hex: "BDBDC6"),
        "Clay Ash": UIColor(hex: "BDC8B3"),
        "Loblolly": UIColor(hex: "BDC9CE"),
        "French Pass": UIColor(hex: "BDEDFD"),
        "London Hue": UIColor(hex: "BEA6C3"),
        "Pink Swan": UIColor(hex: "BEB5B7"),
        "Fuego": UIColor(hex: "BEDE0D"),
        "Rose of Sharon": UIColor(hex: "BF5500"),
        "Tide": UIColor(hex: "BFB8B0"),
        "Blue Haze": UIColor(hex: "BFBED8"),
        "Silver Sand": UIColor(hex: "BFC1C2"),
        "Key Lime Pie": UIColor(hex: "BFC921"),
        "Ziggurat": UIColor(hex: "BFDBE2"),
        "Lime": UIColor(hex: "BFFF00"),
        "Thunderbird": UIColor(hex: "C02B18"),
        "Mojo": UIColor(hex: "C04737"),
        "Old Rose": UIColor(hex: "C08081"),
        "Silver": UIColor(hex: "C0C0C0"),
        "Pale Leaf": UIColor(hex: "C0D3B9"),
        "Pixie Green": UIColor(hex: "C0D8B6"),
        "Tia Maria": UIColor(hex: "C1440E"),
        "Fuchsia Pink": UIColor(hex: "C154C1"),
        "Buddha Gold": UIColor(hex: "C1A004"),
        "Bison Hide": UIColor(hex: "C1B7A4"),
        "Tea": UIColor(hex: "C1BAB0"),
        "Gray Suit": UIColor(hex: "C1BECD"),
        "Sprout": UIColor(hex: "C1D7B0"),
        "Sulu": UIColor(hex: "C1F07C"),
        "Indochine": UIColor(hex: "C26B03"),
        "Twine": UIColor(hex: "C2955D"),
        "Cotton Seed": UIColor(hex: "C2BDB6"),
        "Pumice": UIColor(hex: "C2CAC4"),
        "Jagged Ice": UIColor(hex: "C2E8E5"),
        "Maroon Flush": UIColor(hex: "C32148"),
        "Indian Khaki": UIColor(hex: "C3B091"),
        "Pale Slate": UIColor(hex: "C3BFC1"),
        "Gray Nickel": UIColor(hex: "C3C3BD"),
        "Periwinkle Gray": UIColor(hex: "C3CDE6"),
        "Tiara": UIColor(hex: "C3D1D1"),
        "Tropical Blue": UIColor(hex: "C3DDF9"),
        "Cardinal": UIColor(hex: "C41E3A"),
        "Fuzzy Wuzzy Brown": UIColor(hex: "C45655"),
        "Orange Roughy": UIColor(hex: "C45719"),
        "Mist Gray": UIColor(hex: "C4C4BC"),
        "Coriander": UIColor(hex: "C4D0B0"),
        "Mint Tulip": UIColor(hex: "C4F4EB"),
        "Mulberry": UIColor(hex: "C54B8C"),
        "Nugget": UIColor(hex: "C59922"),
        "Tussock": UIColor(hex: "C5994B"),
        "Sea Mist": UIColor(hex: "C5DBCA"),
        "Yellow Green": UIColor(hex: "C5E17A"),
        "Brick Red": UIColor(hex: "C62D42"),
        "Contessa": UIColor(hex: "C6726B"),
        "Oriental Pink": UIColor(hex: "C69191"),
        "Roti": UIColor(hex: "C6A84B"),
        "Ash": UIColor(hex: "C6C3B5"),
        "Kangaroo": UIColor(hex: "C6C8BD"),
        "Las Palmas": UIColor(hex: "C6E610"),
        "Monza": UIColor(hex: "C7031E"),
        "Red Violet": UIColor(hex: "C71585"),
        "Coral Reef": UIColor(hex: "C7BCA2"),
        "Melrose": UIColor(hex: "C7C1FF"),
        "Cloud": UIColor(hex: "C7C4BF"),
        "Ghost": UIColor(hex: "C7C9D5"),
        "Pine Glade": UIColor(hex: "C7CD90"),
        "Botticelli": UIColor(hex: "C7DDE5"),
        "Antique Brass": UIColor(hex: "C88A65"),
        "Lilac": UIColor(hex: "C8A2C8"),
        "Hokey Pokey": UIColor(hex: "C8A528"),
        "Lily": UIColor(hex: "C8AABF"),
        "Laser": UIColor(hex: "C8B568"),
        "Edgewater": UIColor(hex: "C8E3D7"),
        "Piper": UIColor(hex: "C96323"),
        "Pizza": UIColor(hex: "C99415"),
        "Light Wisteria": UIColor(hex: "C9A0DC"),
        "Rodeo Dust": UIColor(hex: "C9B29B"),
        "Sundance": UIColor(hex: "C9B35B"),
        "Earls Green": UIColor(hex: "C9B93B"),
        "Silver Rust": UIColor(hex: "C9C0BB"),
        "Conch": UIColor(hex: "C9D9D2"),
        "Reef": UIColor(hex: "C9FFA2"),
        "Aero Blue": UIColor(hex: "C9FFE5"),
        "Flush Mahogany": UIColor(hex: "CA3435"),
        "Turmeric": UIColor(hex: "CABB48"),
        "Paris White": UIColor(hex: "CADCD4"),
        "Bitter Lemon": UIColor(hex: "CAE00D"),
        "Skeptic": UIColor(hex: "CAE6DA"),
        "Viola": UIColor(hex: "CB8FA9"),
        "Foggy Gray": UIColor(hex: "CBCAB6"),
        "Green Mist": UIColor(hex: "CBD3B0"),
        "Nebula": UIColor(hex: "CBDBD6"),
        "Persian Red": UIColor(hex: "CC3333"),
        "Burnt Orange": UIColor(hex: "CC5500"),
        "Ochre": UIColor(hex: "CC7722"),
        "Puce": UIColor(hex: "CC8899"),
        "Thistle Green": UIColor(hex: "CCCAA8"),
        "Periwinkle": UIColor(hex: "CCCCFF"),
        "Electric Lime": UIColor(hex: "CCFF00"),
        "Tenn": UIColor(hex: "CD5700"),
        "Chestnut Rose": UIColor(hex: "CD5C5C"),
        "Brandy Punch": UIColor(hex: "CD8429"),
        "Onahau": UIColor(hex: "CDF4FF"),
        "Sorrell Brown": UIColor(hex: "CEB98F"),
        "Cold Turkey": UIColor(hex: "CEBABA"),
        "Yuma": UIColor(hex: "CEC291"),
        "Chino": UIColor(hex: "CEC7A7"),
        "Eunry": UIColor(hex: "CFA39D"),
        "Old Gold": UIColor(hex: "CFB53B"),
        "Tasman": UIColor(hex: "CFDCCF"),
        "Surf Crest": UIColor(hex: "CFE5D2"),
        "Humming Bird": UIColor(hex: "CFF9F3"),
        "Scandal": UIColor(hex: "CFFAF4"),
        "Red Stage": UIColor(hex: "D05F04"),
        "Hopbush": UIColor(hex: "D06DA1"),
        "Meteor": UIColor(hex: "D07D12"),
        "Perfume": UIColor(hex: "D0BEF8"),
        "Prelude": UIColor(hex: "D0C0E5"),
        "Tea Green": UIColor(hex: "D0F0C0"),
        "Geebung": UIColor(hex: "D18F1B"),
        "Vanilla": UIColor(hex: "D1BEA8"),
        "Soft Amber": UIColor(hex: "D1C6B4"),
        "Celeste": UIColor(hex: "D1D2CA"),
        "Mischka": UIColor(hex: "D1D2DD"),
        "Pear": UIColor(hex: "D1E231"),
        "Hot Cinnamon": UIColor(hex: "D2691E"),
        "Raw Sienna": UIColor(hex: "D27D46"),
        "Careys Pink": UIColor(hex: "D29EAA"),
        "Tan": UIColor(hex: "D2B48C"),
        "Deco": UIColor(hex: "D2DA97"),
        "Blue Romance": UIColor(hex: "D2F6DE"),
        "Gossip": UIColor(hex: "D2F8B0"),
        "Sisal": UIColor(hex: "D3CBBA"),
        "Swirl": UIColor(hex: "D3CDC5"),
        "Charm": UIColor(hex: "D47494"),
        "Clam Shell": UIColor(hex: "D4B6AF"),
        "Straw": UIColor(hex: "D4BF8D"),
        "Akaroa": UIColor(hex: "D4C4A8"),
        "Bird Flower": UIColor(hex: "D4CD16"),
        "Iron": UIColor(hex: "D4D7D9"),
        "Geyser": UIColor(hex: "D4DFE2"),
        "Hawkes Blue": UIColor(hex: "D4E2FC"),
        "Grenadier": UIColor(hex: "D54600"),
        "Can Can": UIColor(hex: "D591A4"),
        "Whiskey": UIColor(hex: "D59A6F"),
        "Winter Hazel": UIColor(hex: "D5D195"),
        "Granny Apple": UIColor(hex: "D5F6E3"),
        "My Pink": UIColor(hex: "D69188"),
        "Tacha": UIColor(hex: "D6C562"),
        "Moon Raker": UIColor(hex: "D6CEF6"),
        "Quill Gray": UIColor(hex: "D6D6D1"),
        "Snowy Mint": UIColor(hex: "D6FFDB"),
        "New York Pink": UIColor(hex: "D7837F"),
        "Pavlova": UIColor(hex: "D7C498"),
        "Fog": UIColor(hex: "D7D0FF"),
        "Valencia": UIColor(hex: "D84437"),
        "Japonica": UIColor(hex: "D87C63"),
        "Thistle": UIColor(hex: "D8BFD8"),
        "Maverick": UIColor(hex: "D8C2D5"),
        "Foam": UIColor(hex: "D8FCFA"),
        "Cabaret": UIColor(hex: "D94972"),
        "Burning Sand": UIColor(hex: "D99376"),
        "Cameo": UIColor(hex: "D9B99B"),
        "Timberwolf": UIColor(hex: "D9D6CF"),
        "Tana": UIColor(hex: "D9DCC1"),
        "Link Water": UIColor(hex: "D9E4F5"),
        "Mabel": UIColor(hex: "D9F7FF"),
        "Cerise": UIColor(hex: "DA3287"),
        "Flame Pea": UIColor(hex: "DA5B38"),
        "Bamboo": UIColor(hex: "DA6304"),
        "Red Damask": UIColor(hex: "DA6A41"),
        "Orchid": UIColor(hex: "DA70D6"),
        "Copperfield": UIColor(hex: "DA8A67"),
        "Golden Grass": UIColor(hex: "DAA520"),
        "Zanah": UIColor(hex: "DAECD6"),
        "Iceberg": UIColor(hex: "DAF4F0"),
        "Oyster Bay": UIColor(hex: "DAFAFF"),
        "Cranberry": UIColor(hex: "DB5079"),
        "Petite Orchid": UIColor(hex: "DB9690"),
        "Di Serria": UIColor(hex: "DB995E"),
        "Alto": UIColor(hex: "DBDBDB"),
        "Frosted Mint": UIColor(hex: "DBFFF8"),
        "Crimson": UIColor(hex: "DC143C"),
        "Punch": UIColor(hex: "DC4333"),
        "Galliano": UIColor(hex: "DCB20C"),
        "Blossom": UIColor(hex: "DCB4BC"),
        "Wattle": UIColor(hex: "DCD747"),
        "Westar": UIColor(hex: "DCD9D2"),
        "Moon Mist": UIColor(hex: "DCDDCC"),
        "Caper": UIColor(hex: "DCEDB4"),
        "Swans Down": UIColor(hex: "DCF0EA"),
        "Swiss Coffee": UIColor(hex: "DDD6D5"),
        "White Ice": UIColor(hex: "DDF9F1"),
        "Cerise Red": UIColor(hex: "DE3163"),
        "Roman": UIColor(hex: "DE6360"),
        "Tumbleweed": UIColor(hex: "DEA681"),
        "Gold Tips": UIColor(hex: "DEBA13"),
        "Brandy": UIColor(hex: "DEC196"),
        "Wafer": UIColor(hex: "DECBC6"),
        "Sapling": UIColor(hex: "DED4A4"),
        "Barberry": UIColor(hex: "DED717"),
        "Beryl Green": UIColor(hex: "DEE5C0"),
        "Pattens Blue": UIColor(hex: "DEF5FF"),
        "Heliotrope": UIColor(hex: "DF73FF"),
        "Apache": UIColor(hex: "DFBE6F"),
        "Chenin": UIColor(hex: "DFCD6F"),
        "Lola": UIColor(hex: "DFCFDB"),
        "Willow Brook": UIColor(hex: "DFECDA"),
        "Chartreuse Yellow": UIColor(hex: "DFFF00"),
        "Mauve": UIColor(hex: "E0B0FF"),
        "Anzac": UIColor(hex: "E0B646"),
        "Harvest Gold": UIColor(hex: "E0B974"),
        "Calico": UIColor(hex: "E0C095"),
        "Baby Blue": UIColor(hex: "E0FFFF"),
        "Sunglo": UIColor(hex: "E16865"),
        "Equator": UIColor(hex: "E1BC64"),
        "Pink Flare": UIColor(hex: "E1C0C8"),
        "Periglacial Blue": UIColor(hex: "E1E6D6"),
        "Kidnapper": UIColor(hex: "E1EAD4"),
        "Tara": UIColor(hex: "E1F6E8"),
        "Mandy": UIColor(hex: "E25465"),
        "Terracotta": UIColor(hex: "E2725B"),
        "Golden Bell": UIColor(hex: "E28913"),
        "Shocking": UIColor(hex: "E292C0"),
        "Dixie": UIColor(hex: "E29418"),
        "Light Orchid": UIColor(hex: "E29CD2"),
        "Snuff": UIColor(hex: "E2D8ED"),
        "Mystic": UIColor(hex: "E2EBED"),
        "Apple Green": UIColor(hex: "E2F3EC"),
        "Razzmatazz": UIColor(hex: "E30B5C"),
        "Alizarin Crimson": UIColor(hex: "E32636"),
        "Cinnabar": UIColor(hex: "E34234"),
        "Cavern Pink": UIColor(hex: "E3BEBE"),
        "Peppermint": UIColor(hex: "E3F5E1"),
        "Mindaro": UIColor(hex: "E3F988"),
        "Deep Blush": UIColor(hex: "E47698"),
        "Gamboge": UIColor(hex: "E49B0F"),
        "Melanie": UIColor(hex: "E4C2D5"),
        "Twilight": UIColor(hex: "E4CFDE"),
        "Bone": UIColor(hex: "E4D1C0"),
        "Sunflower": UIColor(hex: "E4D422"),
        "Grain Brown": UIColor(hex: "E4D5B7"),
        "Zombie": UIColor(hex: "E4D69B"),
        "Frostee": UIColor(hex: "E4F6E7"),
        "Snow Flurry": UIColor(hex: "E4FFD1"),
        "Amaranth": UIColor(hex: "E52B50"),
        "Zest": UIColor(hex: "E5841B"),
        "Dust Storm": UIColor(hex: "E5CCC9"),
        "Stark White": UIColor(hex: "E5D7BD"),
        "Hampton": UIColor(hex: "E5D8AF"),
        "Bon Jour": UIColor(hex: "E5E0E1"),
        "Mercury": UIColor(hex: "E5E5E5"),
        "Polar": UIColor(hex: "E5F9F6"),
        "Trinidad": UIColor(hex: "E64E03"),
        "Gold Sand": UIColor(hex: "E6BE8A"),
        "Cashmere": UIColor(hex: "E6BEA5"),
        "Double Spanish White": UIColor(hex: "E6D7B9"),
        "Satin Linen": UIColor(hex: "E6E4D4"),
        "Harp": UIColor(hex: "E6F2EA"),
        "Off Green": UIColor(hex: "E6F8F3"),
        "Hint of Green": UIColor(hex: "E6FFE9"),
        "Tranquil": UIColor(hex: "E6FFFF"),
        "Mango Tango": UIColor(hex: "E77200"),
        "Christine": UIColor(hex: "E7730A"),
        "Tonys Pink": UIColor(hex: "E79F8C"),
        "Kobi": UIColor(hex: "E79FC4"),
        "Rose Fog": UIColor(hex: "E7BCB4"),
        "Corn": UIColor(hex: "E7BF05"),
        "Putty": UIColor(hex: "E7CD8C"),
        "Gray Nurse": UIColor(hex: "E7ECE6"),
        "Lily White": UIColor(hex: "E7F8FF"),
        "Bubbles": UIColor(hex: "E7FEFF"),
        "Fire Bush": UIColor(hex: "E89928"),
        "Shilo": UIColor(hex: "E8B9B3"),
        "Pearl Bush": UIColor(hex: "E8E0D5"),
        "Green White": UIColor(hex: "E8EBE0"),
        "Chrome White": UIColor(hex: "E8F1D4"),
        "Gin": UIColor(hex: "E8F2EB"),
        "Aqua Squeeze": UIColor(hex: "E8F5F2"),
        "Clementine": UIColor(hex: "E96E00"),
        "Burnt Sienna": UIColor(hex: "E97451"),
        "Tahiti Gold": UIColor(hex: "E97C07"),
        "Oyster Pink": UIColor(hex: "E9CECD"),
        "Confetti": UIColor(hex: "E9D75A"),
        "Ebb": UIColor(hex: "E9E3E3"),
        "Ottoman": UIColor(hex: "E9F8ED"),
        "Clear Day": UIColor(hex: "E9FFFD"),
        "Carissma": UIColor(hex: "EA88A8"),
        "Porsche": UIColor(hex: "EAAE69"),
        "Tulip Tree": UIColor(hex: "EAB33B"),
        "Rob Roy": UIColor(hex: "EAC674"),
        "Raffia": UIColor(hex: "EADAB8"),
        "White Rock": UIColor(hex: "EAE8D4"),
        "Panache": UIColor(hex: "EAF6EE"),
        "Solitude": UIColor(hex: "EAF6FF"),
        "Aqua Spring": UIColor(hex: "EAF9F5"),
        "Dew": UIColor(hex: "EAFFFE"),
        "Apricot": UIColor(hex: "EB9373"),
        "Zinnwaldite": UIColor(hex: "EBC2AF"),
        "Fuel Yellow": UIColor(hex: "ECA927"),
        "Ronchi": UIColor(hex: "ECC54E"),
        "French Lilac": UIColor(hex: "ECC7EE"),
        "Just Right": UIColor(hex: "ECCDB9"),
        "Wild Rice": UIColor(hex: "ECE090"),
        "Fall Green": UIColor(hex: "ECEBBD"),
        "Aths Special": UIColor(hex: "ECEBCE"),
        "Starship": UIColor(hex: "ECF245"),
        "Red Ribbon": UIColor(hex: "ED0A3F"),
        "Tango": UIColor(hex: "ED7A1C"),
        "Carrot Orange": UIColor(hex: "ED9121"),
        "Sea Pink": UIColor(hex: "ED989E"),
        "Tacao": UIColor(hex: "EDB381"),
        "Desert Sand": UIColor(hex: "EDC9AF"),
        "Pancho": UIColor(hex: "EDCDAB"),
        "Chamois": UIColor(hex: "EDDCB1"),
        "Primrose": UIColor(hex: "EDEA99"),
        "Frost": UIColor(hex: "EDF5DD"),
        "Aqua Haze": UIColor(hex: "EDF5F5"),
        "Zumthor": UIColor(hex: "EDF6FF"),
        "Narvik": UIColor(hex: "EDF9F1"),
        "Honeysuckle": UIColor(hex: "EDFC84"),
        "Lavender Magenta": UIColor(hex: "EE82EE"),
        "Beauty Bush": UIColor(hex: "EEC1BE"),
        "Chalky": UIColor(hex: "EED794"),
        "Almond": UIColor(hex: "EED9C4"),
        "Flax": UIColor(hex: "EEDC82"),
        "Bizarre": UIColor(hex: "EEDEDA"),
        "Double Colonial White": UIColor(hex: "EEE3AD"),
        "Cararra": UIColor(hex: "EEEEE8"),
        "Manz": UIColor(hex: "EEEF78"),
        "Tahuna Sands": UIColor(hex: "EEF0C8"),
        "Athens Gray": UIColor(hex: "EEF0F3"),
        "Tusk": UIColor(hex: "EEF3C3"),
        "Loafer": UIColor(hex: "EEF4DE"),
        "Catskill White": UIColor(hex: "EEF6F7"),
        "Twilight Blue": UIColor(hex: "EEFDFF"),
        "Jonquil": UIColor(hex: "EEFF9A"),
        "Rice Flower": UIColor(hex: "EEFFE2"),
        "Jaffa": UIColor(hex: "EF863F"),
        "Gallery": UIColor(hex: "EFEFEF"),
        "Porcelain": UIColor(hex: "EFF2F3"),
        "Mauvelous": UIColor(hex: "F091A9"),
        "Golden Dream": UIColor(hex: "F0D52D"),
        "Golden Sand": UIColor(hex: "F0DB7D"),
        "Buff": UIColor(hex: "F0DC82"),
        "Prim": UIColor(hex: "F0E2EC"),
        "Khaki": UIColor(hex: "F0E68C"),
        "Selago": UIColor(hex: "F0EEFD"),
        "Titan White": UIColor(hex: "F0EEFF"),
        "Alice Blue": UIColor(hex: "F0F8FF"),
        "Feta": UIColor(hex: "F0FCEA"),
        "Gold Drop": UIColor(hex: "F18200"),
        "Wewak": UIColor(hex: "F19BAB"),
        "Sahara Sand": UIColor(hex: "F1E788"),
        "Parchment": UIColor(hex: "F1E9D2"),
        "Blue Chalk": UIColor(hex: "F1E9FF"),
        "Mint Julep": UIColor(hex: "F1EEC1"),
        "Seashell": UIColor(hex: "F1F1F1"),
        "Saltpan": UIColor(hex: "F1F7F2"),
        "Tidal": UIColor(hex: "F1FFAD"),
        "Chiffon": UIColor(hex: "F1FFC8"),
        "Flamingo": UIColor(hex: "F2552A"),
        "Tangerine": UIColor(hex: "F28500"),
        "Mandys Pink": UIColor(hex: "F2C3B2"),
        "Concrete": UIColor(hex: "F2F2F2"),
        "Black Squeeze": UIColor(hex: "F2FAFA"),
        "Pomegranate": UIColor(hex: "F34723"),
        "Buttercup": UIColor(hex: "F3AD16"),
        "New Orleans": UIColor(hex: "F3D69D"),
        "Vanilla Ice": UIColor(hex: "F3D9DF"),
        "Sidecar": UIColor(hex: "F3E7BB"),
        "Dawn Pink": UIColor(hex: "F3E9E5"),
        "Wheatfield": UIColor(hex: "F3EDCF"),
        "Canary": UIColor(hex: "F3FB62"),
        "Orinoco": UIColor(hex: "F3FBD4"),
        "Carla": UIColor(hex: "F3FFD8"),
        "Hollywood Cerise": UIColor(hex: "F400A1"),
        "Sandy brown": UIColor(hex: "F4A460"),
        "Saffron": UIColor(hex: "F4C430"),
        "Ripe Lemon": UIColor(hex: "F4D81C"),
        "Janna": UIColor(hex: "F4EBD3"),
        "Pampas": UIColor(hex: "F4F2EE"),
        "Wild Sand": UIColor(hex: "F4F4F4"),
        "Zircon": UIColor(hex: "F4F8FF"),
        "Froly": UIColor(hex: "F57584"),
        "Cream Can": UIColor(hex: "F5C85C"),
        "Manhattan": UIColor(hex: "F5C999"),
        "Maize": UIColor(hex: "F5D5A0"),
        "Wheat": UIColor(hex: "F5DEB3"),
        "Sandwisp": UIColor(hex: "F5E7A2"),
        "Pot Pourri": UIColor(hex: "F5E7E2"),
        "Albescent White": UIColor(hex: "F5E9D3"),
        "Soft Peach": UIColor(hex: "F5EDEF"),
        "Ecru White": UIColor(hex: "F5F3E5"),
        "Beige": UIColor(hex: "F5F5DC"),
        "Golden Fizz": UIColor(hex: "F5FB3D"),
        "Australian Mint": UIColor(hex: "F5FFBE"),
        "French Rose": UIColor(hex: "F64A8A"),
        "Brilliant Rose": UIColor(hex: "F653A6"),
        "Illusion": UIColor(hex: "F6A4C9"),
        "Merino": UIColor(hex: "F6F0E6"),
        "Black Haze": UIColor(hex: "F6F7F7"),
        "Spring Sun": UIColor(hex: "F6FFDC"),
        "Violet Red": UIColor(hex: "F7468A"),
        "Chilean Fire": UIColor(hex: "F77703"),
        "Persian Pink": UIColor(hex: "F77FBE"),
        "Rajah": UIColor(hex: "F7B668"),
        "Azalea": UIColor(hex: "F7C8DA"),
        "We Peep": UIColor(hex: "F7DBE6"),
        "Quarter Spanish White": UIColor(hex: "F7F2E1"),
        "Whisper": UIColor(hex: "F7F5FA"),
        "Snow Drift": UIColor(hex: "F7FAF7"),
        "Casablanca": UIColor(hex: "F8B853"),
        "Chantilly": UIColor(hex: "F8C3DF"),
        "Cherub": UIColor(hex: "F8D9E9"),
        "Marzipan": UIColor(hex: "F8DB9D"),
        "Energy Yellow": UIColor(hex: "F8DD5C"),
        "Givry": UIColor(hex: "F8E4BF"),
        "White Linen": UIColor(hex: "F8F0E8"),
        "Magnolia": UIColor(hex: "F8F4FF"),
        "Spring Wood": UIColor(hex: "F8F6F1"),
        "Coconut Cream": UIColor(hex: "F8F7DC"),
        "White Lilac": UIColor(hex: "F8F7FC"),
        "Desert Storm": UIColor(hex: "F8F8F7"),
        "Texas": UIColor(hex: "F8F99C"),
        "Corn Field": UIColor(hex: "F8FACD"),
        "Mimosa": UIColor(hex: "F8FDD3"),
        "Carnation": UIColor(hex: "F95A61"),
        "Saffron Mango": UIColor(hex: "F9BF58"),
        "Carousel Pink": UIColor(hex: "F9E0ED"),
        "Dairy Cream": UIColor(hex: "F9E4BC"),
        "Portica": UIColor(hex: "F9E663"),
        "Amour": UIColor(hex: "F9EAF3"),
        "Rum Swizzle": UIColor(hex: "F9F8E4"),
        "Dolly": UIColor(hex: "F9FF8B"),
        "Sugar Cane": UIColor(hex: "F9FFF6"),
        "Ecstasy": UIColor(hex: "FA7814"),
        "Tan Hide": UIColor(hex: "FA9D5A"),
        "Corvette": UIColor(hex: "FAD3A2"),
        "Peach Yellow": UIColor(hex: "FADFAD"),
        "Turbo": UIColor(hex: "FAE600"),
        "Astra": UIColor(hex: "FAEAB9"),
        "Champagne": UIColor(hex: "FAECCC"),
        "Linen": UIColor(hex: "FAF0E6"),
        "Fantasy": UIColor(hex: "FAF3F0"),
        "Citrine White": UIColor(hex: "FAF7D6"),
        "Alabaster": UIColor(hex: "FAFAFA"),
        "Hint of Yellow": UIColor(hex: "FAFDE4"),
        "Milan": UIColor(hex: "FAFFA4"),
        "Brink Pink": UIColor(hex: "FB607F"),
        "Geraldine": UIColor(hex: "FB8989"),
        "Lavender Rose": UIColor(hex: "FBA0E3"),
        "Sea Buckthorn": UIColor(hex: "FBA129"),
        "Sun": UIColor(hex: "FBAC13"),
        "Lavender Pink": UIColor(hex: "FBAED2"),
        "Rose Bud": UIColor(hex: "FBB2A3"),
        "Cupid": UIColor(hex: "FBBEDA"),
        "Classic Rose": UIColor(hex: "FBCCE7"),
        "Apricot Peach": UIColor(hex: "FBCEB1"),
        "Banana Mania": UIColor(hex: "FBE7B2"),
        "Marigold Yellow": UIColor(hex: "FBE870"),
        "Festival": UIColor(hex: "FBE96C"),
        "Sweet Corn": UIColor(hex: "FBEA8C"),
        "Candy Corn": UIColor(hex: "FBEC5D"),
        "Hint of Red": UIColor(hex: "FBF9F9"),
        "Shalimar": UIColor(hex: "FBFFBA"),
        "Shocking Pink": UIColor(hex: "FC0FC0"),
        "Tickle Me Pink": UIColor(hex: "FC80A5"),
        "Tree Poppy": UIColor(hex: "FC9C1D"),
        "Lightning Yellow": UIColor(hex: "FCC01E"),
        "Goldenrod": UIColor(hex: "FCD667"),
        "Candlelight": UIColor(hex: "FCD917"),
        "Cherokee": UIColor(hex: "FCDA98"),
        "Double Pearl Lusta": UIColor(hex: "FCF4D0"),
        "Pearl Lusta": UIColor(hex: "FCF4DC"),
        "Vista White": UIColor(hex: "FCF8F7"),
        "Bianca": UIColor(hex: "FCFBF3"),
        "Moon Glow": UIColor(hex: "FCFEDA"),
        "China Ivory": UIColor(hex: "FCFFE7"),
        "Ceramic": UIColor(hex: "FCFFF9"),
        "Torch Red": UIColor(hex: "FD0E35"),
        "Wild Watermelon": UIColor(hex: "FD5B78"),
        "Crusta": UIColor(hex: "FD7B33"),
        "Sorbus": UIColor(hex: "FD7C07"),
        "Sweet Pink": UIColor(hex: "FD9FA2"),
        "Light Apricot": UIColor(hex: "FDD5B1"),
        "Pig Pink": UIColor(hex: "FDD7E4"),
        "Cinderella": UIColor(hex: "FDE1DC"),
        "Golden Glow": UIColor(hex: "FDE295"),
        "Lemon": UIColor(hex: "FDE910"),
        "Old Lace": UIColor(hex: "FDF5E6"),
        "Half Colonial White": UIColor(hex: "FDF6D3"),
        "Drover": UIColor(hex: "FDF7AD"),
        "Pale Prim": UIColor(hex: "FDFEB8"),
        "Cumulus": UIColor(hex: "FDFFD5"),
        "Persian Rose": UIColor(hex: "FE28A2"),
        "Sunset Orange": UIColor(hex: "FE4C40"),
        "Bittersweet": UIColor(hex: "FE6F5E"),
        "California": UIColor(hex: "FE9D04"),
        "Yellow Sea": UIColor(hex: "FEA904"),
        "Melon": UIColor(hex: "FEBAAD"),
        "Bright Sun": UIColor(hex: "FED33C"),
        "Dandelion": UIColor(hex: "FED85D"),
        "Salomie": UIColor(hex: "FEDB8D"),
        "Cape Honey": UIColor(hex: "FEE5AC"),
        "Remy": UIColor(hex: "FEEBF3"),
        "Oasis": UIColor(hex: "FEEFCE"),
        "Bridesmaid": UIColor(hex: "FEF0EC"),
        "Beeswax": UIColor(hex: "FEF2C7"),
        "Bleach White": UIColor(hex: "FEF3D8"),
        "Pipi": UIColor(hex: "FEF4CC"),
        "Half Spanish White": UIColor(hex: "FEF4DB"),
        "Wisp Pink": UIColor(hex: "FEF4F8"),
        "Provincial Pink": UIColor(hex: "FEF5F1"),
        "Half Dutch White": UIColor(hex: "FEF7DE"),
        "Solitaire": UIColor(hex: "FEF8E2"),
        "White Pointer": UIColor(hex: "FEF8FF"),
        "Off Yellow": UIColor(hex: "FEF9E3"),
        "Orange White": UIColor(hex: "FEFCED"),
        "Red": UIColor(hex: "FF0000"),
        "Rose": UIColor(hex: "FF007F"),
        "Purple Pizzazz": UIColor(hex: "FF00CC"),
        "Magenta / Fuchsia": UIColor(hex: "FF00FF"),
        "Scarlet": UIColor(hex: "FF2400"),
        "Wild Strawberry": UIColor(hex: "FF3399"),
        "Razzle Dazzle Rose": UIColor(hex: "FF33CC"),
        "Radical Red": UIColor(hex: "FF355E"),
        "Red Orange": UIColor(hex: "FF3F34"),
        "Coral Red": UIColor(hex: "FF4040"),
        "Vermilion": UIColor(hex: "FF4D00"),
        "International Orange": UIColor(hex: "FF4F00"),
        "Outrageous Orange": UIColor(hex: "FF6037"),
        "Blaze Orange": UIColor(hex: "FF6600"),
        "Pink Flamingo": UIColor(hex: "FF66FF"),
        "Orange": UIColor(hex: "FF681F"),
        "Hot Pink": UIColor(hex: "FF69B4"),
        "Persimmon": UIColor(hex: "FF6B53"),
        "Blush Pink": UIColor(hex: "FF6FFF"),
        "Burning Orange": UIColor(hex: "FF7034"),
        "Pumpkin": UIColor(hex: "FF7518"),
        "Flamenco": UIColor(hex: "FF7D07"),
        "Flush Orange": UIColor(hex: "FF7F00"),
        "Coral": UIColor(hex: "FF7F50"),
        "Salmon": UIColor(hex: "FF8C69"),
        "Pizazz": UIColor(hex: "FF9000"),
        "West Side": UIColor(hex: "FF910F"),
        "Pink Salmon": UIColor(hex: "FF91A4"),
        "Neon Carrot": UIColor(hex: "FF9933"),
        "Atomic Tangerine": UIColor(hex: "FF9966"),
        "Vivid Tangerine": UIColor(hex: "FF9980"),
        "Sunshade": UIColor(hex: "FF9E2C"),
        "Orange Peel": UIColor(hex: "FFA000"),
        "Mona Lisa": UIColor(hex: "FFA194"),
        "Web Orange": UIColor(hex: "FFA500"),
        "Carnation Pink": UIColor(hex: "FFA6C9"),
        "Hit Pink": UIColor(hex: "FFAB81"),
        "Yellow Orange": UIColor(hex: "FFAE42"),
        "Cornflower Lilac": UIColor(hex: "FFB0AC"),
        "Sundown": UIColor(hex: "FFB1B3"),
        "My Sin": UIColor(hex: "FFB31F"),
        "Texas Rose": UIColor(hex: "FFB555"),
        "Cotton Candy": UIColor(hex: "FFB7D5"),
        "Macaroni and Cheese": UIColor(hex: "FFB97B"),
        "Selective Yellow": UIColor(hex: "FFBA00"),
        "Koromiko": UIColor(hex: "FFBD5F"),
        "Amber": UIColor(hex: "FFBF00"),
        "Wax Flower": UIColor(hex: "FFC0A8"),
        "Pink": UIColor(hex: "FFC0CB"),
        "Your Pink": UIColor(hex: "FFC3C0"),
        "Supernova": UIColor(hex: "FFC901"),
        "Flesh": UIColor(hex: "FFCBA4"),
        "Sunglow": UIColor(hex: "FFCC33"),
        "Golden Tainoi": UIColor(hex: "FFCC5C"),
        "Peach Orange": UIColor(hex: "FFCC99"),
        "Chardonnay": UIColor(hex: "FFCD8C"),
        "Pastel Pink": UIColor(hex: "FFD1DC"),
        "Romantic": UIColor(hex: "FFD2B7"),
        "Grandis": UIColor(hex: "FFD38C"),
        "Gold": UIColor(hex: "FFD700"),
        "School bus Yellow": UIColor(hex: "FFD800"),
        "Cosmos": UIColor(hex: "FFD8D9"),
        "Mustard": UIColor(hex: "FFDB58"),
        "Peach Schnapps": UIColor(hex: "FFDCD6"),
        "Caramel": UIColor(hex: "FFDDAF"),
        "Tuft Bush": UIColor(hex: "FFDDCD"),
        "Watusi": UIColor(hex: "FFDDCF"),
        "Pink Lace": UIColor(hex: "FFDDF4"),
        "Navajo White": UIColor(hex: "FFDEAD"),
        "Frangipani": UIColor(hex: "FFDEB3"),
        "Pippin": UIColor(hex: "FFE1DF"),
        "Pale Rose": UIColor(hex: "FFE1F2"),
        "Negroni": UIColor(hex: "FFE2C5"),
        "Cream Brulee": UIColor(hex: "FFE5A0"),
        "Peach": UIColor(hex: "FFE5B4"),
        "Tequila": UIColor(hex: "FFE6C7"),
        "Kournikova": UIColor(hex: "FFE772"),
        "Sandy Beach": UIColor(hex: "FFEAC8"),
        "Karry": UIColor(hex: "FFEAD4"),
        "Broom": UIColor(hex: "FFEC13"),
        "Colonial White": UIColor(hex: "FFEDBC"),
        "Derby": UIColor(hex: "FFEED8"),
        "Vis Vis": UIColor(hex: "FFEFA1"),
        "Egg White": UIColor(hex: "FFEFC1"),
        "Papaya Whip": UIColor(hex: "FFEFD5"),
        "Fair Pink": UIColor(hex: "FFEFEC"),
        "Peach Cream": UIColor(hex: "FFF0DB"),
        "Lavender blush": UIColor(hex: "FFF0F5"),
        "Gorse": UIColor(hex: "FFF14F"),
        "Buttermilk": UIColor(hex: "FFF1B5"),
        "Pink Lady": UIColor(hex: "FFF1D8"),
        "Forget Me Not": UIColor(hex: "FFF1EE"),
        "Tutu": UIColor(hex: "FFF1F9"),
        "Picasso": UIColor(hex: "FFF39D"),
        "Chardon": UIColor(hex: "FFF3F1"),
        "Paris Daisy": UIColor(hex: "FFF46E"),
        "Barley White": UIColor(hex: "FFF4CE"),
        "Egg Sour": UIColor(hex: "FFF4DD"),
        "Sazerac": UIColor(hex: "FFF4E0"),
        "Serenade": UIColor(hex: "FFF4E8"),
        "Chablis": UIColor(hex: "FFF4F3"),
        "Seashell Peach": UIColor(hex: "FFF5EE"),
        "Sauvignon": UIColor(hex: "FFF5F3"),
        "Milk Punch": UIColor(hex: "FFF6D4"),
        "Varden": UIColor(hex: "FFF6DF"),
        "Rose White": UIColor(hex: "FFF6F5"),
        "Baja White": UIColor(hex: "FFF8D1"),
        "Gin Fizz": UIColor(hex: "FFF9E2"),
        "Early Dawn": UIColor(hex: "FFF9E6"),
        "Lemon Chiffon": UIColor(hex: "FFFACD"),
        "Bridal Heath": UIColor(hex: "FFFAF4"),
        "Scotch Mist": UIColor(hex: "FFFBDC"),
        "Soapstone": UIColor(hex: "FFFBF9"),
        "Witch Haze": UIColor(hex: "FFFC99"),
        "Buttery White": UIColor(hex: "FFFCEA"),
        "Island Spice": UIColor(hex: "FFFCEE"),
        "Cream": UIColor(hex: "FFFDD0"),
        "Chilean Heath": UIColor(hex: "FFFDE6"),
        "Travertine": UIColor(hex: "FFFDE8"),
        "Orchid White": UIColor(hex: "FFFDF3"),
        "Quarter Pearl Lusta": UIColor(hex: "FFFDF4"),
        "Half and Half": UIColor(hex: "FFFEE1"),
        "Apricot White": UIColor(hex: "FFFEEC"),
        "Rice Cake": UIColor(hex: "FFFEF0"),
        "Black White": UIColor(hex: "FFFEF6"),
        "Romance": UIColor(hex: "FFFEFD"),
        "Yellow": UIColor(hex: "FFFF00"),
        "Laser Lemon": UIColor(hex: "FFFF66"),
        "Pale Canary": UIColor(hex: "FFFF99"),
        "Portafino": UIColor(hex: "FFFFB4"),
        "Ivory": UIColor(hex: "FFFFF0"),
        "White": UIColor(hex: "FFFFFF")
    ]

    func name() -> String {
        var red: CGFloat = 0
        var green: CGFloat = 0
        var blue: CGFloat = 0
        getRed(&red, green: &green, blue: &blue, alpha: nil)

        let sortedNames = UIColor.names.sorted { (color1Info, color2Info) -> Bool in
            let color1 = color1Info.value.rgba()
            let color1redDiff = abs(red - color1.red)
            let color1greenDiff = abs(green - color1.green)
            let color1blueDiff = abs(blue - color1.blue)
            let total1Diff = color1redDiff + color1greenDiff + color1blueDiff

            let color2 = color2Info.value.rgba()
            let color2redDiff = abs(red - color2.red)
            let color2greenDiff = abs(green - color2.green)
            let color2blueDiff = abs(blue - color2.blue)
            let total2Diff = color2redDiff + color2greenDiff + color2blueDiff

            return total1Diff < total2Diff
        }

        guard let firstColor = sortedNames.first else { fatalError("Colors should contain at least 1 value") }
        return firstColor.key
    }
}
